### PR TITLE
Message from Nikolay

### PR DESCRIPTION
**Pull request by alien190**
Hi Johnny,

How are you? Hope you are doing well.
This message from Nikolay, we cooperated on Upwork. Sorry that I disturb you, but you don't reply on my messages on Upwork.
Johnny, I have to ask you to close our current contract, if you don't mind, of course. The main reason is that open contracts without activity may decrease my rating on the UpWork platform that may negatively affect finding new jobs. Hope for your understanding.
In any case, I'm really happy to work with you. 

Thank you very much.

Kind regards,
Nikolay.

### CODE REVIEW

**Comment by JohnnyNguyen01** [comment]
@alien190 Hey Nikolay!
I remember you, I'm so sorry for the late reply. Thanks for pinging me on github, i'm never on email these days. I'll close that contract, hope you're well and safe!

**Comment by JohnnyNguyen01** [comment]
@alien190 Just completed, please ping me again if you have any questions mate!

**Comment by alien190** [comment]
@JohnnyNguyen01 Hey Johnny!
Thank you very much for the rapid reply and great feedback!
You are really good man, wish you the best with your projects and other spheres of your live!

**Comment by JohnnyNguyen01** [comment]
@alien190 Anytime, glad to see you're doing well!

**Pull request closed without merging**
